version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: jay
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '8080:80'
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./project/:/var/www/project
    restart: always
    depends_on:
      - database
