controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateCont roller::templateAction
    defaults:
        template: home/home.html.twig

about:
    path: /about
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: about/about.html.twig

service:
    path: /service
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: service/service.html.twig

projects:
    path: /projects
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: projects/projects.html.twig

admin:
    path: /admin
    controller: App\Controller\AdminController::home
    methods: GET|POST

tag:
    path: /backoffice
    controller: App\Controller\TagController::createTag
    methods: GET|POST


login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: POST