controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: home/home.html.twig

about:
    path: /about
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: about/about.html.twig

service:
    path: /service
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: service/service.html.twig

projects:
    path: /projects
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: projects/projects.html.twig

admin:
    path: /admin
    controller: App\Controller\AdminController::home
    methods: GET|POST

backoffice:
    path: /backoffice
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: admin/backoffice.html.twig

tag:
    path: /backoffice/tag
    controller: App\Controller\TagController::createTag
    methods: GET|POST

removeTag:
    path: /backoffice/tag/removeTag/{id}
    controller: App\Controller\TagController::removeTag
    methods: GET
    requirements:
        id: '\d+'

editTag:
    path: /backoffice/tag/editTag/{id}
    controller: App\Controller\TagController::editTag
    methods: GET|PUT|POST
    requirements:
        id: '\d+'

edit_tag:
    path: /backoffice/editTag/{id}
    controller: App\Controller\TagController::editTagForm


card:
    path: /backoffice/card
    controller: App\Controller\CardController::createCard
    methods: GET|POST

removeCard:
    path: /backoffice/card/removeCard/{id}
    controller: App\Controller\CardController::removeCard
    methods: GET
    requirements:
        id: '\d+'


editCard:
    path: /backoffice/card/editCard/{id}
    controller: App\Controller\CardController::editCard
    methods: GET|PUT|POST
    requirements:
        id: '\d+'

edit_card:
    path: /backoffice/editCard/{id}
    controller: App\Controller\CardController::editCardForm


login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: POST
