controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

home:
  path: /
  controller: App\Controller\HomeController::home
  methods: GET

mail:
  path: /mail
  controller: App\Controller\MailerController::sendEmail
  methods: POST

about:
  path: /about
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: about/about.html.twig

service:
  path: /service
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: service/service.html.twig

getCardsTags:
  path: /projects
  controller: App\Controller\ProjectController::getCardsTags
  methods: GET

projects:
  path: /projects
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: projects/projects.html.twig

getFilter:
  path: /projects/{id}
  controller: App\Controller\ProjectController::getFilter
  methods: GET
  requirements:
    id: '\d+'








admin:
  path: /admin
  controller: App\Controller\AdminController::home
  methods: GET|POST

backoffice:
  path: /backoffice
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: admin/backoffice.html.twig

tag:
  path: /backoffice/tag
  controller: App\Controller\TagController::createTag
  methods: GET|POST

removeTag:
  path: /backoffice/tag/removeTag/{id}
  controller: App\Controller\TagController::removeTag
  methods: GET
  requirements:
    id: '\d+'

editTag:
  path: /backoffice/tag/editTag/{id}
  controller: App\Controller\TagController::editTag
  methods: GET|PUT|POST
  requirements:
    id: '\d+'


card:
  path: /backoffice/card
  controller: App\Controller\CardController::createCard
  methods: GET|POST

removeCard:
  path: /backoffice/card/removeCard/{id}
  controller: App\Controller\CardController::removeCard
  methods: GET
  requirements:
    id: '\d+'


editCard:
  path: /backoffice/card/editCard/{id}
  controller: App\Controller\CardController::editCard
  methods: GET|PUT|POST
  requirements:
    id: '\d+'


login:
  path: /login
  controller: App\Controller\AuthController::login
  methods: POST
